import { RuleDefinition } from "./types";

export const RULES: RuleDefinition[] = [
  // Security rules
  {
    id: "SEC001",
    name: "hardcoded-secrets",
    description: "Hardcoded API keys, tokens, or passwords",
    category: "security",
    severity: "critical",
    languages: ["typescript", "javascript", "python"],
  },
  {
    id: "SEC002",
    name: "sql-injection",
    description: "SQL injection via string concatenation or template literals",
    category: "security",
    severity: "critical",
    languages: ["typescript", "javascript", "python"],
  },
  {
    id: "SEC003",
    name: "missing-input-validation",
    description: "Express/Fastify route handlers without input validation",
    category: "security",
    severity: "high",
    languages: ["typescript", "javascript"],
  },
  {
    id: "SEC004",
    name: "cors-wildcard",
    description: "CORS configured with wildcard '*' origin",
    category: "security",
    severity: "high",
    languages: ["typescript", "javascript"],
  },
  {
    id: "SEC005",
    name: "unsafe-eval",
    description: "Usage of eval(), exec(), Function() constructor, or dangerouslySetInnerHTML",
    category: "security",
    severity: "critical",
    languages: ["typescript", "javascript", "python"],
  },
  {
    id: "SEC006",
    name: "http-not-https",
    description: "HTTP URLs used in API calls instead of HTTPS",
    category: "security",
    severity: "medium",
    languages: ["typescript", "javascript", "python"],
  },
  // Quality rules
  {
    id: "QUA001",
    name: "unused-imports",
    description: "Imported modules that are never used",
    category: "quality",
    severity: "low",
    languages: ["typescript", "javascript", "python"],
  },
  {
    id: "QUA002",
    name: "empty-catch",
    description: "Empty catch blocks that silently swallow errors",
    category: "quality",
    severity: "medium",
    languages: ["typescript", "javascript"],
  },
  {
    id: "QUA003",
    name: "console-in-production",
    description: "console.log/print statements left in production code",
    category: "quality",
    severity: "low",
    languages: ["typescript", "javascript", "python"],
  },
  {
    id: "QUA004",
    name: "todo-fixme",
    description: "TODO/FIXME comments left by AI generation",
    category: "quality",
    severity: "low",
    languages: ["typescript", "javascript", "python"],
  },
  {
    id: "QUA005",
    name: "magic-numbers",
    description: "Hardcoded magic numbers without named constants",
    category: "quality",
    severity: "low",
    languages: ["typescript", "javascript", "python"],
  },
  // Production readiness rules
  {
    id: "PRD001",
    name: "no-env-management",
    description: "No .env file or environment variable management detected",
    category: "production",
    severity: "medium",
    languages: ["typescript", "javascript", "python"],
  },
  {
    id: "PRD002",
    name: "no-health-check",
    description: "No health check endpoint in server applications",
    category: "production",
    severity: "medium",
    languages: ["typescript", "javascript"],
  },
  {
    id: "PRD003",
    name: "no-graceful-shutdown",
    description: "No graceful shutdown handler (SIGTERM/SIGINT)",
    category: "production",
    severity: "medium",
    languages: ["typescript", "javascript"],
  },
  {
    id: "PRD004",
    name: "no-error-logging",
    description: "No structured logging library — only console.log",
    category: "production",
    severity: "medium",
    languages: ["typescript", "javascript", "python"],
  },
];

export const CATEGORY_WEIGHTS = {
  security: 40,
  quality: 30,
  production: 30,
} as const;
